### ISSUE TITLE
[버그]실시간 해제요청이 정상적으로 되지 않습니다.

### ISSUE THREAD

**Issue by pagloria** [Soju06/python-kis#1]
---
name: 버그 제보
about: 의도 되지 않은 버그를 제보합니다.
title: "실시간 해제요청이 정상적으로 되지 않습니다."
labels: 버그
assignees: ''

---

### 버그 설명
실시간 해제요청이 정상적으로 되지 않습니다.

### 재구현
def _send_request(
        self,
        tr_id: str,
        tr_key: str,
        tr_type: bool,
        timeout: int = 10,
        verbose: bool = True,
    ) -> KisRTSysResponse | None:
        id = self._mkid(tr_id, tr_key)

        if (id in self.subscribed):
            return None

id in self.subscribed 에 의해 구독중인지 확인하는데, 구독중인 종목을 해제하고자 하더라도 None을 반환하고 있습니다.
즉 구독 해제를 요청하기도 전에 None을 반환합니다.

### 원인
if (id in self.subscribed) &(tr_type ==True):
            return None
등으로 수정하면 해결될 것 같습니다.

### 개발 환경
파이썬 버전: 3.11
#### 사용 라이브러리 버전
[귀찮으시면 안 써도 돼요...]
| 이름 | 버전 |
| --- | --- |
| requests | ? |
| SQLAlchemy |  ? |
| websocket-client | ? |
| pycryptodome | ? |
| colorlog | ? |

**Comment by Soju06** [comment]
0bff9b34d4c953932d5ab7115adbe4a8e75a2243 에서 해당 문제를 수정하였습니다.

**Comment by Soju06** [comment]
0bff9b34d4c953932d5ab7115adbe4a8e75a2243 에서 해당 문제를 수정하였습니다.
