### ISSUE TITLE
[질문] 국내주식업종기간별시세를 주석처리하신 이유 질의드립니다

### ISSUE THREAD

**Issue by kgs6546** [Soju06/python-kis#10]
안녕하세요. 좋은 라이브러리 감사드립니다.

튜토리얼대로 진행하던 중, KOSPI 일봉조회를 해보려고 하니, scope/sector/api/period_sector_price를 전부 주석처리 한 것을 확인하였습니다.
해당 주석을 지워서 다시 import해도, 해당 함수들을 여전히 사용할 수 없더라고요.

혹시 업종기간별시세를 다른 함수들을 활용해서, 확인할 수 있는거지, 아니면 해당 함수를 주석처리를 해제하여 다시 활용할 수 있는 방법이 있을까요?

**Comment by Soju06** [comment]
안녕하세요, PyKis를 사용해주셔서 감사드립니다.

질문하신 업종 기간봉 조회는 현재 구현되어있지 않습니다.
정확히는, 업종 관련 기능을 사용할 의도가 없었기 때문에 개발 진행 중 제거하게 되었습니다.
업종 조회를 지원하려면 업종 scope, 관련 api 구현이 필요한 상황입니다.

일부 구현되어있던 업종 기간봉 조회를 사용하려면, 해당 코드 주석을 해제하고, 구형 구조를 수정해야 합니다.
또한 PyKis 클래스에 해당 함수를 import 하거나 직접 해당 함수를 불러와 PyKis객체를 매개변수로 넘겨주며 사용이 필요합니다.

추후 업종 관련 조회 구현해보록 하겠습니다.
