### ISSUE TITLE
[질문] 종목 정보 자동 동기화 여부(market_auto_sync)에 대해 궁금한게 있습니다.

### ISSUE THREAD

**Issue by bongkook** [Soju06/python-kis#14]
### 질문 내용
안녕하세요. 개발자님
종목 정보 자동 동기화 여부(market_auto_sync)를 False로 했을때 실행속도가 빠른거 같아 False로 설정 하려고 합니다.
혹시 False로 해도 문제가 없을까요?
만약 False로 했을때 어떤문제가 발생할지 조언 부탁드립니다.

**Comment by Soju06** [comment]
안녕하세요, PyKis를 사용해주셔서 감사드립니다.

먼저 해당 기능은 PyKis `KisMarketClient`의 종목 목록을 24시간에 한 번씩 자동으로 업데이트하는 파라미터입니다.
종목 목록은 `KisStockScope` 객체를 만드는데 사용되며, PyKis의 거의 대부분 기능(주가 조회, 종목 주문 등)을 이 객체에서 처리하고 있습니다.
즉, scope를 만드는데 사용되는 종목 정보를 가져올 수 없다면 PyKis 사용에 어려움이 있을 수 있습니다.

저 또한 종목 파싱이 느리다는 것을 인지하고 있어, 파싱된 데이터를 sqlite로 `path.join(tempfile.gettempdir(), f".pykis-
cache_market.{MARKET_VERSION}.db")` 경로에 임시저장하고있습니다.
또한, 파일의 저장 시간에 따라 24시간이라는 유효기간으로 업데이트하거나 재사용하도록 작동하고 있습니다.

`market_auto_sync`를 False로 사용해도 정상적으로 작동했던 이유는, 이전에 임시 저장된 데이터를 불러와 사용하고 있기 때문입니다.

이미 저장된 데이터가 있다면 `market_auto_sync`를 오랫 동안 사용하지 않더라도 대부분의 종목에서는 정상적으로 기능을 사용할 수 있습니다. 하지만 저장 날짜 이후 상장된 종목이 있다면 해당 종목에 대해서는 PyKis에서 인식할 수 없는 종목이 됩니다.
만약 종목 자동 동기화 기능을 사용하지 않으시려면 수동으로 `kis.market.sync_all()` 함수를 호출하여 장 종목을 동기화 시켜줘야합니다. 호출의 간격은 본인이 원하는 간격에 따라 동기화시켜주면 됩니다.

해당 질문과 동일한 질문에 대한 답변을 참고하여주세요. [자동 종목 파싱 기능 제거 방법 #7](https://github.com/Soju06/python-kis/issues/7)

추가적인 질문이 있다면 언제든지 질문하셔도 됩니다.

**Comment by bongkook** [comment]
답변 주셔서 감사합니다.
새로고침 주기를 파라미터로 설정하는 기능이 추가되면 유용할꺼 같습니다.
해외주식 관련해서도 체결가 조회, 잔고조회 기능이 추가 되었으면 좋겠습니다.
감사합니다.
