### ISSUE TITLE
[질문] thread _at_sync 의 무한 생성 현상

### ISSUE THREAD

**Issue by jhyunetp** [Soju06/python-kis#19]
안녕하세요. 모의계좌를 포함해서 5개 정도의 계정을 하나의 process에서 돌려보았는데,
메모리 누수 현상이 나타났고, 원인을 파악해보니 thread가 지속적으로 생성되는 것을 확인했습니다.

아마도 캐싱한 종목 정보들을 업데이트하는 과정에서 발생하는 것 같은데, 

Q1. 혹시 제가 코드를 짧은 시간 동안 파악하고 만든 솔루션이 맞을지 여쭤보고 싶습니다.

1. 5개의 계정 중에서 1개를 마스터 계정으로 지정하고, auto_sync를 허용한다. 나머지는auto_sync=False를 적용한다.
2. 모든 계정은 market_database_path를 동일하게 가져간다.
![쓰레드 무한대](https://github.com/Soju06/python-kis/assets/40058848/9545b271-84dd-454b-9873-a230904b256d)

**Comment by Soju06** [comment]
안녕하세요, PyKis 버그를 제보해주셔서 감사드립니다.
알려주신 문제는 #21 에서 수정하였습니다.
