### ISSUE TITLE
[버그] balance_all() 함수에 무한루프 현상이 존재합니다.

### ISSUE THREAD

**Issue by jhyunetp** [Soju06/python-kis#20]
### 버그 설명
일부 계좌에서 balance_all() 함수에 무한루프 현상이 존재합니다.

- WARN API rate limit exceeded. waiting... 가 반복됩니다.

### 재구현

주식잔고조회 API 호출 후 50 개 이상의 종목이 있는 경우에
연속 조회가 이루어지는데, 연속 조회 과정에서 Loop에 빠지는 것 같습니다.

해당 테스트 계좌는 정확히 50종목만 보유한 계좌입니다.

### 원인
while loop에 빠져서 나오질 못함

### 개발 환경
파이썬 버전: 3.10

**Comment by jhyunetp** [comment]
안녕하세요 소유주님, API 자체의 오류 같아보여 일단 포럼에 질의를 하고 있는 상황입니다.

주식잔고조회 API 호출 후 50 개 이상의 종목이 있는 경우에

response.headers["tr_cont"] == "M"을 확인한 이후에, 

headers["tr_cont"] = "N" 헤더에 N을 담아서

추가 데이터를 요청하니 

'rt_cd':'7'
'msg_cd':'SYDB0050'
'msg1':'조회이후에 자료가 변경되었습니다.(다시 조회하세요)

라고 뜹니다. 위와 같은 반응만 반복됩니다.

위에서 발생하는 오류로 보입니다. 추가로 공유하겠습니다.

**Comment by jhyunetp** [comment]
![balance debug](https://github.com/Soju06/python-kis/assets/40058848/a185b3f3-6e3d-43ee-9fb4-fae5414c59c0)
`"tr_cont" : "N" if page.search != "" else "" # 다음 페이지가 있는 경우, N을 입력하고 아니라면 비워놓는다.`

일단 이렇게 제거하고 사용하고 있습니다. 혹시 소유주님께 도움이 되실까 하여 공유드립니다.

**Comment by Soju06** [comment]
시간 내어 원인을 찾아주셔서 감사합니다.
현재 라이브러리를 개편하면서, 국내 및 해외 구분 없이 동일한 인터페이스로 쿼리할 수 있는 기능이 개발되었습니다.
해당 버그 또한 v2에서 해결되어, `2.0.1`버전으로 라이브러리로 업데이트 하시고 이용해주시면 됩니다.

```shell
pip install python-kis --upgrade
```

[Tutorial#3.1. 예수금 및 보유 종목 조회](https://github.com/Soju06/python-kis/wiki/Tutorial#31-%EC%98%88%EC%88%98%EA%B8%88-%EB%B0%8F-%EB%B3%B4%EC%9C%A0-%EC%A2%85%EB%AA%A9-%EC%A1%B0%ED%9A%8C) 문서를 참고하여 예수금 및 보유종목을 조회하실 수 있습니다.

```python
from pykis import PyKis

kis = PyKis("secret.json", keep_token=True)
account = kis.account()

balance = account.balance()

print(repr(balance)) # repr을 통해 객체의 주요 내용을 확인할 수 있습니다.
```

```python
KisIntegrationBalance(
    account_number=KisAccountNumber('50113500-01'),
    deposits={
        'KRW': KisDomesticDeposit(account_number=KisAccountNumber('50113500-01'), currency='KRW', amount=2447692, exchange_rate=1),
        'USD': KisForeignPresentDeposit(account_number=KisAccountNumber('50113500-01'), currency='USD', amount=0, exchange_rate=1384.6),
    },
    stocks=[
        KisDomesticBalanceStock(account_number=KisAccountNumber('50113500-01'), market='KRX', symbol='000660', qty=14, price=192600, amount=2696400, profit=22900, profit_rate=0.856555077613615111277351786),
        KisDomesticBalanceStock(account_number=KisAccountNumber('50113500-01'), market='KRX', symbol='039200', qty=118, price=39600, amount=4672800, profit=-199500, profit_rate=-4.094575457176282248630010467)
    ],
    purchase_amount=7545800,
    current_amount=7369200,
    profit=-176600,
    profit_rate=-2.340374778022211031302181346
)
```
