### ISSUE TITLE
[질문] token expire 설정

### ISSUE THREAD

**Issue by jonggwan** [Soju06/python-kis#23]
만들어주신 패키지 잘쓰고 있습니다.
제가 주기적으로 주가를 체크하는데, 이게 PyKis를 생성할 때마다 새로 token이 만들어지고 이것 때문에 카카오톡이 그 때마다 날아오네요. 생성시 token expires_in을 설정하는 방법이 있을까요? 아니면 PyKis object를 pickle/redis로 캐싱해서 쓰는 것이 가능할까요?

**Comment by Soju06** [comment]
안녕하세요, PyKis를 사용해 주셔서 감사드립니다.

먼저, 한국투자증권의 API 문서 [접근토큰발급(P)[인증-001]](https://apiportal.koreainvestment.com/apiservice/oauth2#L_fa778c98-f68d-451e-8fff-b1c6bfe5cd30) 처럼 따로 expires_in을 설정하는 방법은 없어 보입니다.

그렇기에 토큰 발급 이후 24시간이 지나면 무조건 다시 발급받아야합니다.

질문해 주신 주기적인 주가 체크의 간격을 알 수 없어, 두 가지의 상황과 그에 따른 해결 방안에 대해 설명하겠습니다.

1. 24시간 상시 실행 중인 파이썬 프로그램
    해당 조건은 높은 확률로 PyKis 객체를 재사용이 가능한 환경일 것입니다.
    PyKis는 자체적으로 토큰의 유효를 관리하므로 하나의 PyKis 객체를 생성하고 토큰이 만료될 때까지 토큰을 재활용할 것입니다.

2. 변수 유지가 어려운 On-Demand 시스템
    질문해 주신 내용을 보면 아마도 해당 환경으로 보입니다.
    만약 하루에 두 번 이상 실행되는 시스템인 경우 토큰을 캐싱하여 현재 문제를 해결할 수 있습니다.
    하지만 질문의 내용처럼 PyKis 객체 전체를 직렬화하는 것은 예기치 못한 문제가 발생할 수 있기 때문에 좋지 않은 방법입니다.
    
    아래의 코드처럼 토큰만 따로 저장하고 다시 불러오는 것이 좋을 듯합니다.


    토큰 저장:

    ```py
    import json
    from pykis import PyKis

    kis = PyKis(
        # 앱 키  예) Pa0knAM6JLAjIa93Miajz7ykJIXXXXXXXXXX
        appkey=APPKEY,
        # 앱 시크릿  예) V9J3YGPE5q2ZRG5EgqnLHn7XqbJjzwXcNpvY . . .
        appsecret=APPSECRET,
        # 가상 계좌 여부
        virtual_account=False,
    )

    # PyKis 객체를 생성하고, API를 호출해야만 토큰을 발급받습니다.
    kis.stock('005490').price()

    if kis.client.token:
        # 토큰을 파일로 저장합니다.
        with open('token.json', 'w') as f:
            json.dump({
                'token': kis.client.token.token,
                'token_type': kis.client.token.token_type,
                'expires_in': kis.client.token.expires_in,
                'timestamp': kis.client.token.timestamp.isoformat(),
                'expires_at': kis.client.token.expires_at.isoformat(),
                'empty': False,
            }, f)
    ```

    토큰 로드:

    ```py
    from datetime import datetime
    import json
    from pykis import KisAccessToken, PyKis

    kis = PyKis(
        # 앱 키  예) Pa0knAM6JLAjIa93Miajz7ykJIXXXXXXXXXX
        appkey=APPKEY,
        # 앱 시크릿  예) V9J3YGPE5q2ZRG5EgqnLHn7XqbJjzwXcNpvY . . .
        appsecret=APPSECRET,
        # 가상 계좌 여부
        virtual_account=False,
    )

    with open('token.json', 'r') as f:
        token = json.load(f)
        token['timestamp'] = datetime.fromisoformat(token['timestamp'])
        token['expires_at'] = datetime.fromisoformat(token['expires_at'])
        kis.client.token = KisAccessToken(kis)
        kis.client.token.__dict__.update(token)

    # 시세 조회
    kis.stock('005490').price()
    ```

또한 현재 개발 중인 [pykis-v2](https://github.com/Soju06/python-kis/tree/pykis-v2) 버전도 한 번 참고해 보시면 좋을 것 같습니다.

시세 조회 이외의 기능은 아직 구현되지 않았지만, 원하시는 시세 조회에 관련된 시스템은 현재 PyKis보다 더욱 사용하기 편리해졌습니다.

[example.ipynb](https://github.com/Soju06/python-kis/blob/pykis-v2/example.ipynb) 파일을 참고해 주세요.

**Comment by jonggwan** [comment]
@Soju06 자세한 설명 감사드립니다. 제 나름데로 token.py 에서 파일과 redis를 쓰게 변형해서 사용하고 있습니다. 위 코드도 잘 참고하겠습니다.
