### ISSUE TITLE
[질문] 한투에서 접근토큰 발급 변경으로 에러가 발생합니다.

### ISSUE THREAD

**Issue by bongkook** [Soju06/python-kis#24]
### 질문 내용
한투에서 10월27일 17시 이후로 접근 토큰 발급변경으로 1분당 1회씩만 호출가능하도록 변경되어
API내에서 매번 토큰을 발급하기 때문에 1분내에 다시 호출하면 에러가 발생합니다.
해결방법이 있을까요?

**Comment by bongkook** [comment]
아래와 같은 에러가 발생합니다.
msg_cd: EGW00133 
msg1: 접근토큰발급 잠시후 다시 시도하세요(1분당 1회)

아래의 공지를 보니 10월17일에 공지가 떴네요.
https://apiportal.koreainvestment.com/intro
대응방법에 대해 알려 주시면 감사하겠습니다.

**Comment by wollala** [comment]
`kis = PyKis(
    # 앱 키  예) Pa0knAM6JLAjIa93Miajz7ykJIXXXXXXXXXX
    appkey=APPKEY,
    # 앱 시크릿  예) V9J3YGPE5q2ZRG5EgqnLHn7XqbJjzwXcNpvY . . .
    appsecret=APPSECRET,
    # 가상 계좌 여부
    virtual_account=True,
    # 실시간 조회 비활성화
    realtime=False
)`
이런식으로 받으신 키를 계속 다시 부르지 말고, 한투에서 6시간정도까지는 토큰이 유지된다고 하니
singleton class 등을 활용하여 한번 받아놓으신  토큰을 유지한테 계속 사용하시는 방법으로 코드를 변경하시면 될 듯 싶습니다.

**Comment by bongkook** [comment]
네 답변 감사합니다.
