### ISSUE TITLE
[질문] 인버스에 period_price를 적용 시 발생하는 " ValueError: 주식이 아닙니다. " 문제

### ISSUE THREAD

**Issue by jhyunetp** [Soju06/python-kis#26]
### 질문 내용
인버스 pykis.scope.stock.stock.KisStockScope object at 0x00000262A1C46BC0> 종목코드 114800 객체에
stock.period_price를 적용 시 발생하는 " ValueError: 주식이 아닙니다. " 오류가 발생합니다.

혹시 주식과 같이 기간봉을 받을 수 있는 방법이 있을까요?

ETF 에 적용하면 문제가 생겨서 위와 같은 예외처리를 넣으신 것인지 궁금합니다.

**Comment by Soju06** [comment]
안녕하세요.
현재 라이브러리를 개편하면서, 국내 및 해외 구분 없이 동일한 인터페이스로 쿼리할 수 있는 기능이 개발되었습니다.
해당 버그 또한 v2에서 해결되어, `2.0.1`버전으로 라이브러리로 업데이트 하시고 이용해주시면 됩니다.
```shell
pip install python-kis --upgrade
```

[Tutorial#2.2. 차트 조회](https://github.com/Soju06/python-kis/wiki/Tutorial#22-%EC%B0%A8%ED%8A%B8-%EC%A1%B0%ED%9A%8C) 문서를 보시고, 원하는 데이터를 추출 하실 수 있습니다.

```python
from pykis import PyKis

kis = PyKis(
    id="soju06", # 앱키를 발급받은 HTS ID
    account="50113500-01", # 계좌번호
    appkey="PSED321z7A9l...", # 앱 키
    secretkey="RR0sFMVBIH50F...", # 앱 시크릿 키
    keep_token=True,
)

kodex_inv = kis.stock("114800")
sqqq = kis.stock("SQQQ")

kodex_inv_chart = kodex_inv.chart(period=1)  # 1분봉
sqqq_chart = sqqq.chart(period=5)  # 5분봉
# kodex_inv_chart = kodex_inv.chart("7d") # 7일간 일봉 조회
# sqqq_chart = sqqq.chart("1y", period="month") # 1년간 월봉 조회


# pandas DataFrame으로도 변환할 수 있습니다.
print(kodex_inv_chart.df())

for bar in kodex_inv_chart.bars:
    print(bar.time, bar.open, bar.high, bar.low, bar.close, bar.volume)
```
