### ISSUE TITLE
[질문] 당일 분봉 데이터를 가지고 오는 기능이 있는지요?

### ISSUE THREAD

**Issue by freegear-sc** [Soju06/python-kis#29]
### 기능 설명
안녕하세요.

좋은 라이브러리 공개해 주셔서 고맙습니다.
잘 사용하고 있습니다.

예제에 없어서 그런제 기능이 아직 구현이 안된 것으로 보여서 문의 드립니다.

당일 분봉 데이터를 가지고 오는 기능이 있는지요 ?

추가를 하고 싶어서, 
코드를 보았는데, 제 능력으로는 어려워서 요청을 드립니다.

감사합니다.

**Comment by freegear-sc** [comment]
바쁘시면 가이드를 주시면 제가 시도 해 보겠습니다.
감사합니다.

**Comment by Soju06** [comment]
안녕하세요.
현재 라이브러리를 개편하면서, API 구분 없이 시세조회, 주문 등을 할 수 있는 기능이 개발되었습니다.
당일분봉, 기간봉 등을 통합으로 조회할 수 있는 `2.0.1`버전으로 라이브러리로 업데이트 하시고 이용해주시면 됩니다.

```sh
pip install python-kis --upgrade
```

[Tutorial#2.2. 차트 조회](https://github.com/Soju06/python-kis/wiki/Tutorial#22-%EC%B0%A8%ED%8A%B8-%EC%A1%B0%ED%9A%8C) 문서를 보시고, 원하는 데이터를 추출 하실 수 있습니다.

```python
from pykis import PyKis

kis = PyKis(
    id="soju06", # 앱키를 발급받은 HTS ID
    account="50113500-01", # 계좌번호
    appkey="PSED321z7A9l...", # 앱 키
    secretkey="RR0sFMVBIH50F...", # 앱 시크릿 키
    keep_token=True,
)

hynix = kis.stock("000660")
nvidia = kis.stock("NVDA")

hynix_chart = hynix.chart(period=1) # 1분봉
nvidia_chart = nvidia.chart(period=5) # 5분봉
# hynix_chart = hynix.chart("7d") # 7일간 일봉 조회
# nvidia_chart = nvidia.chart("1y", period="month") # 1년간 월봉 조회


# pandas DataFrame으로도 변환할 수 있습니다.
print(hynix_chart.df())

for bar in hynix_chart.bars:
    print(bar.time, bar.open, bar.high, bar.low, bar.close, bar.volume)
```

**Comment by freegear-sc** [comment]
정말 감사합니다.  요새 다른 프로젝트로 너무 정신없이 하다가 이제서야 봤습니다. 
- 강제로 코드를 고쳐서 쓰고 있었습니다.^^
