### ISSUE TITLE
[질문] 이패키지가.. 한국투자 증권 공식 라이브러리 입니까?

### ISSUE THREAD

**Issue by mic-user** [Soju06/python-kis#31]
한국 투자 증권 전산실에서 공식 작성해서 배포하는 라이브러리인가요?

**Comment by Soju06** [comment]
한국투자증권 전산실과 연관 없는 커뮤니티 라이브러리입니다.
한국투자증권에서 공식적으로 개발한 파이썬 라이브러리는 없는 것으로 알고 있습니다.
