### ISSUE TITLE
[질문]: 시크릿 키를 직접 입력하는 방법에서 모의투자 사용시 실전투자 api 키와 시크릿키를 같이 입력하는 이유가 있나요?

### ISSUE THREAD

**Issue by bongkook** [Soju06/python-kis#39]
### 빠른 문제 해결을 위해 다음을 확인했나요?

- [X] PyKis [Issues](https://github.com/Soju06/python-kis/issues)에서 검색했지만 유사한 질문을 찾지 못했습니다.

### 질문 내용

안녕하세요.

오래간만에 버전업이 되어서 둘러보고 있는데 의문점이 있어 연락 드립니다.
시크릿 키를 직접 입력하는 방법에서 모의투자 사용시 실전투자 api 키와 시크릿키를 같이 입력하는 이유가 있나요?
그리고 이전버전에 없던 HTS 아이디 입력이 필수인데 왜 그런지 궁금합니다.
가능하면 모의투자 사용시에는 실전투자 api 키와 시크릿키를 입력하고 싶지 않습니다.
그리고 HTS 아이디도 없이 사용할수 있으면 좋겠네요.

업데이트 해주셔서 감사합니다.

**Comment by Soju06** [comment]
안녕하세요.
python-kis의 `kis.stock()` 함수를 포함한 대부분의 조회는 실전 도메인의 [[국내주식] 종목정보 상품기본조회[v1_국내주식-029]](https://apiportal.koreainvestment.com/apiservice/apiservice-domestic-stock-information#L_00589d46-b8fe-4329-a20e-50dfe05f0d82) API를 활용하고 있습니다.
최근, API의 실전 및 모의 도메인 검증이 강화되어 모의투자 환경에서 해당 API를 사용할 수 없게 되었습니다.
이로 인해 단순히 실전 앱키를 보조로 활용하는 구조로 변경하였습니다.

HTS ID를 필수사항으로 변경한 이유는 아래 코드처럼 라이브러리의 새로운 디자인 패턴을 활용하기 위해 변경하였습니다.
```python
account = kis.account()
stock = kis.stock('000660')

def on_execution(sender: KisWebsocketClient, e: KisSubscriptionEventArgs[KisRealtimeExecution]):
    print(e.response)

with account.on("execution", on_execution) as ticket:  # 계좌 전체 실시간 체결 조회
    input()

with stock.on("execution", on_execution) as ticket:  # SK하이닉스 실시간 체결 조회
    input()
```
라이브러리 자체의 HTS ID 검증은 없기 때문에 실시간 체결 조회 기능을 활용하지 않는다면, 더미 값으로 설정하셔도 무방합니다.

[KIS Developers Q&A](https://apiportal.koreainvestment.com/community/10000000-0000-0011-0000-000000000003)의 `모의투자 상품기본조회` 문의를 참고해주세요.

**Comment by bongkook** [comment]
빠른 답변 대단히 감사합니다.
