### ISSUE TITLE
[버그]:  withdrawable이나 withdrawable_amount 모두 총자산금액을 return 하네요... 

### ISSUE THREAD

**Issue by honnae1** [Soju06/python-kis#40]
### 빠른 문제 해결을 위해 다음을 확인했나요?

- [X] PyKis [Issues](https://github.com/Soju06/python-kis/issues)에서 검색했지만 유사한 버그를 찾지 못했습니다.

### 버그 설명

예제대로 따라가고 있습니다..
balance=kis.account().balance()
출금가능금액이  필요해 api/account/balance.py 내용 참고 하며 테스트중인데요..
제목 내용대로 balance. withdrawable=balance. withdrawable_amount=balance.deposits['KRW'].amout 모두 예수금을 리턴하네요. 만드신 파일 서칭중인데 달리 가능한 방법은 못찾겠어서 문의 드립니다. 

### 종속성 버전 문제 진단

2.0.2 부터 pykis.utils 없어지지 않았나요??

### 재현 방법

bal=kis.account().balance()
print('withdrawable:', bal.withdrawable)
print('[KRW].amount:', bal.deposits['KRW'].amount)
print('withdrawable_amount:', bal.withdrawable_amount)
print('deposits[KRW].withdrawable_amount:',self.kisObj.domestic_orderable_amount())
#모두 같은 금액이네요..??

### 추가 정보

``

### PR를 통해 라이브러리에 기여하고 싶으신가요?

- [ ] 네, PR을 제출하여 도움을 주고 싶습니다!

**Comment by Soju06** [comment]
안녕하세요.
현재 국내 잔고 조회의 경우 [[국내주식] 주문/계좌 -> 주식잔고조회[v1_국내주식-006]](https://apiportal.koreainvestment.com/apiservice/apiservice-domestic-stock-order#L_66c61080-674f-4c91-a0cc-db5e64e9a5e6) API를 사용하여 구현되어있습니다.
해외 잔고 조회와 다르게 해당 API에서는 출금가능금액을 제공해주지 않고 있습니다.
이로 인해, `python-kis`에서는 아래와 같이 원화 예수금의 출금가능금액은 예수금과 동일하게 대체해놓은 상태입니다.
```python
amount: Decimal = KisDecimal["dnca_tot_amt"]
"""예수금"""
withdrawable_amount: Decimal = KisDecimal["dnca_tot_amt"]
"""출금가능금액"""
```

원화 출금가능금액 조회가 필요하시다면, 한국투자증권 개발자 포럼에 문의하셔야 할 것 같습니다.

**Comment by honnae1** [comment]
답변 감사드립니다.. 
따로 답장을 주셨는데 일부 옮기면 아래 내용입니다. open kis에서 지원하지 않는다는 내용으로 이해했습니다.

''현재 국내 잔고 조회의 경우 [국내주식] 주문/계좌 -> 주식잔고조회[v1_국내주식-006] API를 사용하여 구현되어있습니다.
해외 잔고 조회와 다르게 해당 API에서는 출금가능금액을 제공해주지 않고 있습니다.
이로 인해, python-kis에서는 아래와 같이 원화 예수금의 출금가능금액은 예수금과 동일하게 대체해놓은 상태입니다.''
