### ISSUE TITLE
[질문]: 모의투자용 PyKis 객체를 생성하기 위해 실전투자용 시크릿 키 파일이 꼭 필요한지요?

### ISSUE THREAD

**Issue by jpkong** [Soju06/python-kis#46]
### 빠른 문제 해결을 위해 다음을 확인했나요?

- [X] PyKis [Issues](https://github.com/Soju06/python-kis/issues)에서 검색했지만 유사한 질문을 찾지 못했습니다.

### 질문 내용

모의투자만 진행하려고 하는데도, 불필요한 인증정보인 실전 투자용 시크릿 키 파일이 필요해서 좀 불편합니다.
확인 부탁드립니다.

**Comment by Soju06** [comment]
Duplicate of #39
