### ISSUE TITLE
[질문] kis.market.kospi.all() 기능 중 거래 불가 종목 제거 가능 여부 질의드립니다.

### ISSUE THREAD

**Issue by jhyunetp** [Soju06/python-kis#9]
안녕하세요. 

좋은 라이브러리를 공유해주셔서 감사드립니다.

kis.market.kospi.all()
kis.market.kosdaq.all()
을 사용하고 있는데

이지스229호 Class A 와 같이, 사실상 거래가 불가능한 데이터들이 많이 나와서 해당 어떻게 제거해야할지 고민 중에 있습니다.

1. return 객체에 kospi_issu_yn는 코스피에 상장되었는지를 나타내는 것이 맞을까요? 
2. kosdaq_issu_yu은 데이터가 따로 없는데 혹시 코스닥에 거래 가능한지 확인할 수 있는 방법이 있을까요?

1번과 2번을 확인하여 "kospi_issu_yn and kospi_issu_yn" 인 종목만 선별하려고 합니다.

3. 위의 방법론이 개발 의도에 맞는지 질문드리고 싶습니다.

**Comment by Soju06** [comment]
안녕하세요, PyKis를 사용해주셔서 감사드립니다.
저도 자료가 부족하였기에 아래 답변 내용이 정확하지 않을 수 있습니다.

1. `kospi_issu_yn`은 테스트해 본 결과 "코스피에 상장되었는지"를 나타내는 것으로 보입니다.
    하지만 정확히 말하면, 종목이 코스피에 상장되었다는 것은 반드시 거래가 가능하다는 것을 의미하지 않을 수 있습니다.
    어떤 종목들은 상장은 되어 있지만 거래정지 상태일 수 있습니다. 이를 확인하려면 `trht_yn`(거래정지여부) 등의 추가적인 정보를 참조해야 할 수 있습니다.
3. `kosdaq_issu_yn`의 경우 관련된 정보가 공식 자료에서도 존재하지 않았습니다.
    kospi의 경우 해당 정보가 있는 것을 확인하였지만, kosdaq은 비슷한 정보가 없는 것 같습니다.
4. 현재 라이브러리에는 해당 기능 구현되어 있지 않기에 위 정보를 이용하여 거래 가능 종목을 선별하는 것은 좋은 방법이라고 생각합니다.

추가로, 아래는 제가 참고한 자료입니다.
[종목마스터정보(코스닥).h](https://github.com/koreainvestment/open-trading-api/blob/main/stocks_info/%EC%A2%85%EB%AA%A9%EB%A7%88%EC%8A%A4%ED%84%B0%EC%A0%95%EB%B3%B4(%EC%BD%94%EC%8A%A4%EB%8B%A5).h)
[종목마스터정보(코스피).h](https://github.com/koreainvestment/open-trading-api/blob/main/stocks_info/%EC%A2%85%EB%AA%A9%EB%A7%88%EC%8A%A4%ED%84%B0%EC%A0%95%EB%B3%B4(%EC%BD%94%EC%8A%A4%ED%94%BC).h)

**Comment by jhyunetp** [comment]
네 상세한 설명 감사드립니다.
현재로선 kospi_issu_yn와 코드의 시작과 끝이 numeric한지 여부를 가지고 일단 필터링하고 있습니다.
